services:
  stripe:
    image: stripe/stripe-cli:latest
    container_name: stripe_cli
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    command: >
      listen
      --forward-to host.docker.internal:3333/api/stripe/webhook
      --log-level debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
